import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, BellRing, CalendarClock, CheckCircle2, Copy, Edit3, History, ImagePlus, Layers3, Loader2, Megaphone, MousePointerClick, Pause, Play, RefreshCw, Rocket, Search, Send, Upload, XCircle } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { uploadYamoCampaignMedia, yamoRowsNewest, yamoRpc } from "@/lib/yamo-admin";

type Kind = "banner" | "instant_message";
type Draft = { kind: Kind; titleAr: string; titleEn: string; bodyAr: string; bodyEn: string; imageUrl: string; destinationType: string; destinationValue: string; segment: string; placement: string; buttonAr: string; buttonEn: string; scheduledAt: string; endsAt: string; enabled: boolean; showText: boolean };
const start: Draft = { kind:"banner", titleAr:"", titleEn:"", bodyAr:"", bodyEn:"", imageUrl:"", destinationType:"room", destinationValue:"", segment:"all", placement:"home", buttonAr:"عرض الآن", buttonEn:"View now", scheduledAt:"", endsAt:"", enabled:true, showText:true };
const destinations = [["room","غرفة"],["event","حدث"],["activity","فعالية"],["user","مستخدم"],["agency","وكالة"],["page","صفحة داخل التطبيق"]];
const legacyBanners = [
  { image:"asset://home_banner_voice", preview:"/legacy-banners/home_banner_voice_1029x540.webp", title:"صوتك ليه مكان", body:"ادخل غرف يامو وشارك بصوتك", destination:"room" },
  { image:"asset://home_banner_posts", preview:"/legacy-banners/home_banner_posts_1029x540.webp", title:"شارك لحظتك", body:"صور وفيديوهات من مجتمع يامو", destination:"page", value:"posts" },
  { image:"asset://home_banner_event", preview:"/legacy-banners/home_banner_event_1029x540.webp", title:"حدث اليوم", body:"العب وتحدّى واربح جوائز مميزة", destination:"event" },
  { image:"asset://home_banner_agency", preview:"/legacy-banners/home_banner_agency_1029x540.webp", title:"وكالتك في يامو", body:"تابع فريقك وإنجازاتك", destination:"agency" },
  { image:"asset://home_banner_vip", preview:"/legacy-banners/home_banner_vip_1029x540.webp", title:"مزايا VIP الحصرية", body:"إطارات ودخوليات ومكافآت مميزة", destination:"page", value:"vip" },
];
const previewImage=(url:string)=>legacyBanners.find(item=>item.image===url)?.preview??url;
type Lookup = { found:boolean; title?:string; subtitle?:string; image_url?:string; status?:string; message?:string };
const toLocal=(value:unknown)=>value?new Date(String(value)).toISOString().slice(0,16):"";
const fromRow=(r:Record<string,unknown>):Draft=>({kind:r.kind as Kind,titleAr:String(r.title_ar??""),titleEn:String(r.title_en??""),bodyAr:String(r.body_ar??""),bodyEn:String(r.body_en??""),imageUrl:String(r.image_url??""),destinationType:String(r.destination_type??"page"),destinationValue:String(r.destination_value??""),segment:String(r.segment??"all"),placement:String(r.placement??"home"),buttonAr:String(r.button_ar??""),buttonEn:String(r.button_en??""),scheduledAt:toLocal(r.scheduled_at),endsAt:toLocal(r.ends_at),enabled:r.enabled===true,showText:r.content_mode!=="image"});

function CampaignsPage() {
  const [draft,setDraft]=useState<Draft>(start); const [uploading,setUploading]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [lookup,setLookup]=useState<Lookup|null>(null); const [looking,setLooking]=useState(false); const [showHistory,setShowHistory]=useState(false); const qc=useQueryClient();
  const campaigns=useQuery({queryKey:["yamo-admin","admin_yamo_campaigns","banners"],queryFn:async()=>(await yamoRowsNewest("admin_yamo_campaigns",100)).filter(row=>row.kind==="banner")});
  const history=useQuery({queryKey:["yamo-admin","admin_yamo_campaign_history"],queryFn:()=>yamoRowsNewest("admin_yamo_campaign_history",100),enabled:showHistory});
  const stats=useMemo(()=>{const rows=campaigns.data??[];return{active:rows.filter(r=>r.lifecycle_status==="active").length,sent:rows.reduce((n,r)=>n+Number(r.sent_count??0),0),clicks:rows.reduce((n,r)=>n+Number(r.click_count??0),0)}},[campaigns.data]);
  const set=<K extends keyof Draft>(key:K,value:Draft[K])=>{setDraft(old=>({...old,[key]:value}));if(key==="destinationType"||key==="destinationValue")setLookup(null)};
  const args={p_kind:draft.kind,p_title_ar:draft.titleAr,p_title_en:draft.titleEn||null,p_body_ar:draft.bodyAr,p_body_en:draft.bodyEn||null,p_image_url:draft.imageUrl||null,p_destination_type:draft.destinationType,p_destination_value:draft.destinationValue||null,p_segment:draft.segment,p_placement:draft.kind==="banner"?draft.placement:null,p_button_ar:draft.buttonAr||null,p_button_en:draft.buttonEn||null,p_scheduled_at:draft.scheduledAt?new Date(draft.scheduledAt).toISOString():null,p_ends_at:draft.endsAt?new Date(draft.endsAt).toISOString():null,p_enabled:draft.enabled,p_content_mode:draft.showText?"image_text":"image"};
  const payload={title_ar:args.p_title_ar,title_en:args.p_title_en,body_ar:args.p_body_ar,body_en:args.p_body_en,image_url:args.p_image_url,destination_type:args.p_destination_type,destination_value:args.p_destination_value,segment:args.p_segment,placement:args.p_placement,button_ar:args.p_button_ar,button_en:args.p_button_en,scheduled_at:args.p_scheduled_at??new Date().toISOString(),ends_at:args.p_ends_at,enabled:args.p_enabled,content_mode:args.p_content_mode};
  const save=useMutation({mutationFn:()=>editingId?yamoRpc("admin_update_yamo_campaign",{p_id:editingId,p_payload:payload}):yamoRpc("admin_save_yamo_campaign",args),onSuccess:async()=>{toast.success(editingId?"تم حفظ التعديلات":"تم نشر الحملة");setEditingId(null);setDraft(start);setLookup(null);await qc.invalidateQueries({queryKey:["yamo-admin"]})},onError:(e:Error)=>toast.error(e.message)});
  const changeState=async(id:string,enabled:boolean|null,archive=false)=>{if(archive&&!window.confirm("نقل الحملة للأرشيف؟ ستظل محفوظة مع كامل سجلها."))return;try{await yamoRpc("admin_set_yamo_campaign_state",{p_id:id,p_enabled:enabled,p_delete:archive});toast.success(archive?"تمت الأرشفة بدون حذف":"تم تحديث الحالة");await qc.invalidateQueries({queryKey:["yamo-admin"]})}catch(e){toast.error(e instanceof Error?e.message:"تعذر تحديث الحملة")}};
  const lookupDestination=async()=>{setLooking(true);try{const result=await yamoRpc<Lookup>("admin_lookup_yamo_campaign_destination",{p_type:draft.destinationType,p_value:draft.destinationValue});setLookup(result);result.found?toast.success("تم العثور على الوجهة"):toast.error(result.message??"الوجهة غير موجودة")}catch(e){toast.error(e instanceof Error?e.message:"تعذر البحث")}finally{setLooking(false)}};
  const edit=(row:Record<string,unknown>,copy=false)=>{setDraft(fromRow(row));setEditingId(copy?null:String(row.id));setLookup(null);window.scrollTo({top:0,behavior:"smooth"});toast.success(copy?"تم تحميل نسخة جديدة":"تم تحميل الحملة للتعديل")};
  const renew=async(id:string)=>{const answer=window.prompt("عدد أيام التجديد: 1 أو 3 أو 7 أو 30، أو أي عدد", "7");if(!answer)return;const days=Number(answer);if(!Number.isInteger(days)||days<1){toast.error("اكتب عدد أيام صحيح");return}try{await yamoRpc("admin_renew_yamo_campaign",{p_id:id,p_days:days,p_ends_at:null});toast.success(`تم التجديد ${days.toLocaleString("en-US")} يوم`);await qc.invalidateQueries({queryKey:["yamo-admin"]})}catch(e){toast.error(e instanceof Error?e.message:"تعذر التجديد")}};
  const upload=async(file?:File)=>{if(!file)return;setUploading(true);try{set("imageUrl",await uploadYamoCampaignMedia(file));toast.success("تم رفع الصورة")}catch(e){toast.error(e instanceof Error?e.message:"تعذر رفع الصورة")}finally{setUploading(false)}};
  return <div className="space-y-5" dir="rtl">
    <div className="grid gap-3 md:grid-cols-3"><Stat icon={Rocket} label="الحملات النشطة" value={stats.active}/><Stat icon={BellRing} label="تم الإرسال" value={stats.sent}/><Stat icon={MousePointerClick} label="إجمالي الضغطات" value={stats.clicks}/></div>
    <div><h1 className="text-3xl font-black">إدارة البنرات</h1><p className="text-muted-foreground">قسم مستقل للبنرات فقط — المقاس المعتمد 1029 × 540</p></div>
    <Editor title={editingId?"تعديل البنر":"إنشاء بنر جديد"} description="صورة أو نص وصورة مع معاينة الوجهة الحقيقية" {...{draft,set,upload,uploading,lookup,looking,lookupDestination}} saving={save.isPending} submit={()=>save.mutate()} editing={!!editingId} cancel={()=>{setEditingId(null);setDraft(start);setLookup(null)}}/>
    <Card className="border-orange-500/15"><CardHeader><CardTitle className="flex items-center gap-2"><Layers3 className="h-5 w-5 text-orange-500"/>البنرات القديمة</CardTitle><CardDescription>البنرات الأصلية موجودة ويمكن إعادة نشر أي واحد منها أو تعديل نصه ووجهته</CardDescription></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{legacyBanners.map(item=><button type="button" key={item.image} onClick={()=>setDraft(old=>({...old,kind:"banner",imageUrl:item.image,titleAr:item.title,bodyAr:item.body,destinationType:item.destination,destinationValue:item.value??"",showText:true}))} className="overflow-hidden rounded-2xl border bg-card text-right transition hover:-translate-y-1 hover:border-violet-400 hover:shadow-xl"><img src={item.preview} alt={item.title} className="aspect-[1029/540] w-full object-cover"/><div className="p-3"><p className="font-black">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">اضغط للتحميل في المحرر</p></div></button>)}</div></CardContent></Card>
    <Card className="overflow-hidden border-violet-500/15"><CardHeader className="flex-row items-center justify-between"><div><CardTitle>إدارة الحملات</CardTitle><CardDescription>تعديل ونسخ وتجديد وإيقاف وأرشفة بدون حذف نهائي</CardDescription></div><Button variant="outline" onClick={()=>setShowHistory(v=>!v)}><History className="ml-2 h-4 w-4"/>سجل العمليات</Button></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[1250px] text-sm"><thead><tr className="border-b text-muted-foreground"><th className="p-3 text-right">النوع</th><th className="p-3 text-right">العنوان</th><th className="p-3 text-right">الوجهة</th><th className="p-3 text-right">البداية</th><th className="p-3 text-right">النهاية</th><th className="p-3 text-right">الحالة</th><th className="p-3 text-right">الإرسال</th><th className="p-3 text-right">الإجراءات</th></tr></thead><tbody>{(campaigns.data??[]).map(row=><tr key={String(row.id)} className="border-b last:border-0"><td className="p-3">{row.kind==="banner"?"بنر":"رسالة فورية"}</td><td className="p-3 font-bold">{String(row.title_ar??"—")}</td><td className="p-3">{String(row.destination_type??"—")} {row.destination_value?`• ${row.destination_value}`:""}</td><td className="p-3 font-mono text-xs">{row.scheduled_at?new Date(String(row.scheduled_at)).toLocaleString("en-GB"):"فوري"}</td><td className="p-3 font-mono text-xs">{row.ends_at?new Date(String(row.ends_at)).toLocaleString("en-GB"):"مستمرة"}</td><td className="p-3"><Status value={String(row.lifecycle_status??(row.enabled?"active":"stopped"))}/></td><td className="p-3 font-mono">{Number(row.sent_count??0).toLocaleString("en-US")}</td><td className="p-3"><div className="flex flex-wrap gap-1"><Mini icon={Edit3} label="تعديل" onClick={()=>edit(row)}/><Mini icon={Copy} label="نسخ" onClick={()=>edit(row,true)}/><Mini icon={RefreshCw} label="تجديد" onClick={()=>renew(String(row.id))}/><Mini icon={row.enabled?Pause:Play} label={row.enabled?"إيقاف":"تشغيل"} onClick={()=>changeState(String(row.id),!row.enabled)}/><Mini icon={Archive} label="أرشفة" danger onClick={()=>changeState(String(row.id),null,true)}/></div></td></tr>)}</tbody></table></CardContent></Card>
    {showHistory&&<Card><CardHeader><CardTitle>سجل العمليات الكامل</CardTitle><CardDescription>التعديلات والتشغيل والإيقاف والتجديد والأرشفة محفوظة</CardDescription></CardHeader><CardContent className="space-y-2">{(history.data??[]).map(row=><div key={String(row.id)} className="flex items-center justify-between rounded-xl border p-3"><div><b>{String(row.title_ar??"حملة")}</b><span className="mr-2 rounded-lg bg-violet-500/10 px-2 py-1 text-xs text-violet-600">{String(row.action)}</span></div><span className="font-mono text-xs">{new Date(String(row.created_at)).toLocaleString("en-GB")}</span></div>)}</CardContent></Card>}
  </div>;
}

function Editor({title,description,draft,set,upload,uploading,saving,submit,lookup,looking,lookupDestination,editing,cancel}:{title:string;description:string;draft:Draft;set:<K extends keyof Draft>(key:K,value:Draft[K])=>void;upload:(file?:File)=>void;uploading:boolean;saving:boolean;submit:()=>void;lookup:Lookup|null;looking:boolean;lookupDestination:()=>void;editing:boolean;cancel:()=>void}) {
  return <Card className="mt-4 overflow-hidden border-violet-500/20 shadow-xl shadow-violet-500/5"><CardHeader className="bg-gradient-to-l from-violet-500/10 to-orange-500/5"><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent className="grid gap-5 p-5 lg:grid-cols-[1fr_1.05fr]"><div className="space-y-4">
    <SectionTitle number="1" title="المحتوى"/><Field label="العنوان العربي"><Input value={draft.titleAr} onChange={e=>set("titleAr",e.target.value)}/></Field><Field label="النص العربي — يظهر تحت الصورة"><textarea className="min-h-24 w-full rounded-xl border bg-background p-3 text-sm" value={draft.bodyAr} onChange={e=>set("bodyAr",e.target.value)}/></Field>
    <div className="grid gap-3 sm:grid-cols-2"><Field label="العنوان الإنجليزي"><Input value={draft.titleEn} onChange={e=>set("titleEn",e.target.value)}/></Field><Field label="زر الإجراء"><Input value={draft.buttonAr} onChange={e=>set("buttonAr",e.target.value)}/></Field></div>
    <SectionTitle number="2" title="الصورة"/><Field label="صورة الحملة"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-violet-400/30 bg-violet-500/5 p-5 font-bold text-violet-600 hover:bg-violet-500/10"><input type="file" accept="image/*" className="hidden" onChange={e=>upload(e.target.files?.[0])}/>{uploading?<Loader2 className="h-5 w-5 animate-spin"/>:<Upload className="h-5 w-5"/>}{uploading?"جاري الرفع":"ارفع صورة 1029 × 540"}</label></Field><Field label="أو رابط الصورة"><Input value={draft.imageUrl} onChange={e=>set("imageUrl",e.target.value)} dir="ltr"/></Field>
  </div><div className="space-y-4">
    <SectionTitle number="3" title="المعاينة المباشرة"/><div className="overflow-hidden rounded-3xl border bg-card shadow-lg">{draft.imageUrl?<img src={previewImage(draft.imageUrl)} alt="معاينة" className="aspect-[1029/540] w-full object-cover"/>:<div className="grid aspect-[1029/540] place-items-center bg-muted/20 text-muted-foreground"><div className="text-center"><ImagePlus className="mx-auto mb-2 h-8 w-8"/>المعاينة تظهر هنا فورًا</div></div>}{draft.showText&&<div className="p-4"><p className="text-lg font-black">{draft.titleAr||"عنوان الحملة"}</p><p className="mt-1 text-sm text-muted-foreground">{draft.bodyAr||"النص سيظهر هنا تحت الصورة"}</p><span className="mt-3 inline-flex rounded-xl bg-gradient-to-l from-orange-500 to-violet-600 px-4 py-2 text-xs font-bold text-white">{draft.buttonAr||"عرض الآن"}</span></div>}</div>
    <SectionTitle number="4" title="الوجهة والجمهور"/><div><Label className="mb-2 block font-black">الوجهة عند الضغط</Label><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{destinations.map(([v,l])=><button type="button" key={v} onClick={()=>set("destinationType",v)} className={`rounded-xl border p-3 text-sm font-bold transition ${draft.destinationType===v?"border-violet-500 bg-violet-500/10 text-violet-600 shadow-md":"hover:border-violet-300"}`}>{l}</button>)}</div></div>
    <Field label={draft.destinationType==="page"?"اسم الصفحة: posts / rooms / messages / profile / vip / tasks":"ID الوجهة"}><div className="flex gap-2"><Input value={draft.destinationValue} onChange={e=>set("destinationValue",e.target.value)} dir="ltr"/><Button type="button" variant="outline" disabled={looking||!draft.destinationValue} onClick={lookupDestination}>{looking?<Loader2 className="ml-2 h-4 w-4 animate-spin"/>:<Search className="ml-2 h-4 w-4"/>}بحث</Button></div></Field>
    {lookup&&<div className={`flex items-center gap-3 rounded-2xl border p-3 ${lookup.found?"border-emerald-400 bg-emerald-500/5":"border-red-400 bg-red-500/5"}`}>{lookup.found?<CheckCircle2 className="h-5 w-5 text-emerald-600"/>:<XCircle className="h-5 w-5 text-red-600"/>}{lookup.image_url&&<img src={lookup.image_url} alt="" className="h-12 w-12 rounded-xl object-cover"/>}<div><p className="font-black">{lookup.title??lookup.message}</p><p className="text-xs text-muted-foreground">{lookup.subtitle} {lookup.status&&`• ${lookup.status}`}</p></div></div>}
    <div className="grid gap-3 sm:grid-cols-2"><Field label="الجمهور"><Select value={draft.segment} onChange={v=>set("segment",v)} options={[["all","كل المستخدمين"],["vip","VIP"],["hosts","المضيفون"],["male","الذكور"],["female","الإناث"]]}/></Field>{draft.kind==="banner"&&<Field label="مكان الظهور"><Select value={draft.placement} onChange={v=>set("placement",v)} options={[["home","الرئيسية"],["rooms","الغرف"],["messages","الرسائل"]]}/></Field>}</div>
    <SectionTitle number="5" title="الجدولة الحديثة"/><div className="rounded-2xl border bg-gradient-to-l from-violet-500/5 to-orange-500/5 p-4"><div className="mb-3 flex items-center gap-2"><CalendarClock className="h-5 w-5 text-violet-600"/><span className="font-black">{draft.scheduledAt?"نشر مجدول":"نشر فوري"}</span></div><div className="grid gap-3 sm:grid-cols-2"><Field label="تاريخ ووقت البداية"><Input type="datetime-local" value={draft.scheduledAt} onChange={e=>set("scheduledAt",e.target.value)}/></Field><Field label="تاريخ ووقت الانتهاء"><Input type="datetime-local" value={draft.endsAt} onChange={e=>set("endsAt",e.target.value)}/></Field></div><p className="mt-3 text-xs text-muted-foreground">اترك تاريخ البداية فارغًا للنشر فورًا، وتاريخ الانتهاء فارغًا للاستمرار بدون مدة محددة.</p></div>
    <div className="grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={draft.enabled} onChange={e=>set("enabled",e.target.checked)}/><span className="font-bold">الحملة نشطة</span></label><label className="flex items-center gap-3 rounded-xl border p-3"><input type="checkbox" checked={draft.showText} onChange={e=>set("showText",e.target.checked)}/><span className="font-bold">عرض النص فوق الصورة</span></label></div>
    <div className="flex gap-2"><Button type="button" disabled={saving||!lookup?.found||(draft.kind==="banner"&&!draft.imageUrl)||(!draft.titleAr&&!draft.imageUrl)} onClick={submit} className="h-12 flex-1 rounded-2xl bg-gradient-to-l from-orange-500 via-pink-500 to-violet-600 text-white shadow-lg shadow-violet-500/25">{saving?<Loader2 className="ml-2 h-4 w-4 animate-spin"/>:draft.kind==="banner"?<Rocket className="ml-2 h-4 w-4"/>:<Send className="ml-2 h-4 w-4"/>}{editing?"حفظ التعديلات":draft.kind==="banner"?"نشر البنر الآن":"إرسال الرسالة"}</Button>{editing&&<Button type="button" variant="outline" className="h-12" onClick={cancel}>إلغاء</Button>}</div>
    {!lookup?.found&&<p className="text-center text-xs font-bold text-orange-600">ابحث عن الوجهة وتأكد من ظهورها لتفعيل زر النشر.</p>}
  </div></CardContent></Card>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function SectionTitle({number,title}:{number:string;title:string}){return <div className="flex items-center gap-2 pt-1"><span className="grid h-7 w-7 place-items-center rounded-lg bg-violet-600 text-xs font-black text-white">{number}</span><h3 className="font-black">{title}</h3></div>}
function Select({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:string[][]}){return <select value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-xl border bg-background px-3 text-sm">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
function Stat({icon:Icon,label,value}:{icon:typeof Megaphone;label:string;value:number}){return <Card className="border-violet-500/15"><CardContent className="flex items-center gap-4 p-4"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-orange-500 to-violet-600 text-white shadow-lg"><Icon className="h-5 w-5"/></div><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-black">{value.toLocaleString("en-US")}</p></div></CardContent></Card>}
function Status({value}:{value:string}){const map:Record<string,[string,string]>={active:["نشط","bg-emerald-500/10 text-emerald-600"],scheduled:["مجدول","bg-blue-500/10 text-blue-600"],expired:["منتهي","bg-orange-500/10 text-orange-600"],stopped:["متوقف","bg-muted text-muted-foreground"],archived:["مؤرشف","bg-red-500/10 text-red-600"]};const [label,cls]=map[value]??[value,"bg-muted"];return <span className={`rounded-full px-3 py-1 text-xs font-bold ${cls}`}>{label}</span>}
function Mini({icon:Icon,label,onClick,danger}:{icon:typeof Edit3;label:string;onClick:()=>void;danger?:boolean}){return <Button size="sm" variant="outline" className={danger?"text-red-600":""} onClick={onClick}><Icon className="ml-1 h-3.5 w-3.5"/>{label}</Button>}
export const Route=createFileRoute("/_authenticated/banners")({component:CampaignsPage});
