/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWithdrawalsRouteImport } from './routes/_authenticated/withdrawals'
import { Route as AuthenticatedWalletAdjustmentsRouteImport } from './routes/_authenticated/wallet-adjustments'
import { Route as AuthenticatedVipLevelsRouteImport } from './routes/_authenticated/vip-levels'
import { Route as AuthenticatedVerificationsRouteImport } from './routes/_authenticated/verifications'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSupportTicketsRouteImport } from './routes/_authenticated/support-tickets'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityCheckRouteImport } from './routes/_authenticated/security-check'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRelationshipsRouteImport } from './routes/_authenticated/relationships'
import { Route as AuthenticatedPostsRouteImport } from './routes/_authenticated/posts'
import { Route as AuthenticatedPearlPurchasesRouteImport } from './routes/_authenticated/pearl-purchases'
import { Route as AuthenticatedPearlCoinExchangesRouteImport } from './routes/_authenticated/pearl-coin-exchanges'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSystemMessagesRouteImport } from './routes/_authenticated/system-messages'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHostsRouteImport } from './routes/_authenticated/hosts'
import { Route as AuthenticatedHostTransferRequestsRouteImport } from './routes/_authenticated/host-transfer-requests'
import { Route as AuthenticatedGiftsRouteImport } from './routes/_authenticated/gifts'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFamiliesRouteImport } from './routes/_authenticated/families'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedEconomyRouteImport } from './routes/_authenticated/economy'
import { Route as AuthenticatedDistinctiveIdsRouteImport } from './routes/_authenticated/distinctive-ids'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyLoginRouteImport } from './routes/_authenticated/daily-login'
import { Route as AuthenticatedChargingPricingRouteImport } from './routes/_authenticated/charging-pricing'
import { Route as AuthenticatedChargingPearlTransfersRouteImport } from './routes/_authenticated/charging-pearl-transfers'
import { Route as AuthenticatedChargingCoinTransfersRouteImport } from './routes/_authenticated/charging-coin-transfers'
import { Route as AuthenticatedChargingAgentsRouteImport } from './routes/_authenticated/charging-agents'
import { Route as AuthenticatedChargingAgenciesRouteImport } from './routes/_authenticated/charging-agencies'
import { Route as AuthenticatedBdRouteImport } from './routes/_authenticated/bd'
import { Route as AuthenticatedBannersRouteImport } from './routes/_authenticated/banners'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAppReleasesRouteImport } from './routes/_authenticated/app-releases'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAgenciesRouteImport } from './routes/_authenticated/agencies'
import { Route as AuthenticatedAdminsRouteImport } from './routes/_authenticated/admins'
import { Route as AuthenticatedAccountDeletionsRouteImport } from './routes/_authenticated/account-deletions'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated/users.$id'
import { Route as AuthenticatedHostsIdRouteImport } from './routes/_authenticated/hosts.$id'
import { Route as AuthenticatedFinanceWithdrawalSettingsRouteImport } from './routes/_authenticated/finance.withdrawal-settings'
import { Route as AuthenticatedFinanceWithdrawalRequestsRouteImport } from './routes/_authenticated/finance.withdrawal-requests'
import { Route as AuthenticatedFinanceReportsRouteImport } from './routes/_authenticated/finance.reports'
import { Route as AuthenticatedFinanceRechargeRequestsRouteImport } from './routes/_authenticated/finance.recharge-requests'
import { Route as AuthenticatedFinancePearlPricesRouteImport } from './routes/_authenticated/finance.pearl-prices'
import { Route as AuthenticatedFinancePaymentMethodsRouteImport } from './routes/_authenticated/finance.payment-methods'
import { Route as AuthenticatedFinancePackagesRouteImport } from './routes/_authenticated/finance.packages'
import { Route as AuthenticatedFinanceGatewaysRouteImport } from './routes/_authenticated/finance.gateways'
import { Route as AuthenticatedFinanceCoinPricesRouteImport } from './routes/_authenticated/finance.coin-prices'
import { Route as AuthenticatedChargingAgentsIdRouteImport } from './routes/_authenticated/charging-agents.$id'
import { Route as AuthenticatedChargingAgenciesIdRouteImport } from './routes/_authenticated/charging-agencies.$id'
import { Route as AuthenticatedBdIdRouteImport } from './routes/_authenticated/bd.$id'
import { Route as AuthenticatedAgenciesIdRouteImport } from './routes/_authenticated/agencies.$id'
import { Route as AuthenticatedAdminsInvitesRouteImport } from './routes/_authenticated/admins.invites'
import { Route as AuthenticatedFinanceRechargeRefundsIndexRouteImport } from './routes/_authenticated/finance.recharge-refunds.index'
import { Route as AuthenticatedFinanceRechargeRequestsIdRouteImport } from './routes/_authenticated/finance.recharge-requests.$id'
import { Route as AuthenticatedFinanceRechargeRefundsIdRouteImport } from './routes/_authenticated/finance.recharge-refunds.$id'
import { Route as AuthenticatedFinancePackagesIdRouteImport } from './routes/_authenticated/finance.packages.$id'
import { Route as ApiPublicWebhooksPaymentsGatewayIdRefundsRouteImport } from './routes/api/public/webhooks/payments/$gatewayId.refunds'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawalsRoute =
  AuthenticatedWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletAdjustmentsRoute =
  AuthenticatedWalletAdjustmentsRouteImport.update({
    id: '/wallet-adjustments',
    path: '/wallet-adjustments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipLevelsRoute = AuthenticatedVipLevelsRouteImport.update({
  id: '/vip-levels',
  path: '/vip-levels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerificationsRoute =
  AuthenticatedVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportTicketsRoute =
  AuthenticatedSupportTicketsRouteImport.update({
    id: '/support-tickets',
    path: '/support-tickets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityCheckRoute =
  AuthenticatedSecurityCheckRouteImport.update({
    id: '/security-check',
    path: '/security-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelationshipsRoute =
  AuthenticatedRelationshipsRouteImport.update({
    id: '/relationships',
    path: '/relationships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostsRoute = AuthenticatedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPearlPurchasesRoute =
  AuthenticatedPearlPurchasesRouteImport.update({
    id: '/pearl-purchases',
    path: '/pearl-purchases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPearlCoinExchangesRoute =
  AuthenticatedPearlCoinExchangesRouteImport.update({
    id: '/pearl-coin-exchanges',
    path: '/pearl-coin-exchanges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemMessagesRoute =
  AuthenticatedSystemMessagesRouteImport.update({
    id: '/system-messages',
    path: '/system-messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostsRoute = AuthenticatedHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostTransferRequestsRoute =
  AuthenticatedHostTransferRequestsRouteImport.update({
    id: '/host-transfer-requests',
    path: '/host-transfer-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGiftsRoute = AuthenticatedGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamiliesRoute = AuthenticatedFamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEconomyRoute = AuthenticatedEconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistinctiveIdsRoute =
  AuthenticatedDistinctiveIdsRouteImport.update({
    id: '/distinctive-ids',
    path: '/distinctive-ids',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyLoginRoute = AuthenticatedDailyLoginRouteImport.update({
  id: '/daily-login',
  path: '/daily-login',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChargingPricingRoute =
  AuthenticatedChargingPricingRouteImport.update({
    id: '/charging-pricing',
    path: '/charging-pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChargingPearlTransfersRoute =
  AuthenticatedChargingPearlTransfersRouteImport.update({
    id: '/charging-pearl-transfers',
    path: '/charging-pearl-transfers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChargingCoinTransfersRoute =
  AuthenticatedChargingCoinTransfersRouteImport.update({
    id: '/charging-coin-transfers',
    path: '/charging-coin-transfers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChargingAgentsRoute =
  AuthenticatedChargingAgentsRouteImport.update({
    id: '/charging-agents',
    path: '/charging-agents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChargingAgenciesRoute =
  AuthenticatedChargingAgenciesRouteImport.update({
    id: '/charging-agencies',
    path: '/charging-agencies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBdRoute = AuthenticatedBdRouteImport.update({
  id: '/bd',
  path: '/bd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBannersRoute = AuthenticatedBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppReleasesRoute =
  AuthenticatedAppReleasesRouteImport.update({
    id: '/app-releases',
    path: '/app-releases',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgenciesRoute = AuthenticatedAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminsRoute = AuthenticatedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountDeletionsRoute =
  AuthenticatedAccountDeletionsRouteImport.update({
    id: '/account-deletions',
    path: '/account-deletions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedHostsIdRoute = AuthenticatedHostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedHostsRoute,
} as any)
const AuthenticatedFinanceWithdrawalSettingsRoute =
  AuthenticatedFinanceWithdrawalSettingsRouteImport.update({
    id: '/withdrawal-settings',
    path: '/withdrawal-settings',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceWithdrawalRequestsRoute =
  AuthenticatedFinanceWithdrawalRequestsRouteImport.update({
    id: '/withdrawal-requests',
    path: '/withdrawal-requests',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceReportsRoute =
  AuthenticatedFinanceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceRechargeRequestsRoute =
  AuthenticatedFinanceRechargeRequestsRouteImport.update({
    id: '/recharge-requests',
    path: '/recharge-requests',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinancePearlPricesRoute =
  AuthenticatedFinancePearlPricesRouteImport.update({
    id: '/pearl-prices',
    path: '/pearl-prices',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinancePaymentMethodsRoute =
  AuthenticatedFinancePaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinancePackagesRoute =
  AuthenticatedFinancePackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceGatewaysRoute =
  AuthenticatedFinanceGatewaysRouteImport.update({
    id: '/gateways',
    path: '/gateways',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceCoinPricesRoute =
  AuthenticatedFinanceCoinPricesRouteImport.update({
    id: '/coin-prices',
    path: '/coin-prices',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedChargingAgentsIdRoute =
  AuthenticatedChargingAgentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedChargingAgentsRoute,
  } as any)
const AuthenticatedChargingAgenciesIdRoute =
  AuthenticatedChargingAgenciesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedChargingAgenciesRoute,
  } as any)
const AuthenticatedBdIdRoute = AuthenticatedBdIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBdRoute,
} as any)
const AuthenticatedAgenciesIdRoute = AuthenticatedAgenciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAgenciesRoute,
} as any)
const AuthenticatedAdminsInvitesRoute =
  AuthenticatedAdminsInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedAdminsRoute,
  } as any)
const AuthenticatedFinanceRechargeRefundsIndexRoute =
  AuthenticatedFinanceRechargeRefundsIndexRouteImport.update({
    id: '/recharge-refunds/',
    path: '/recharge-refunds/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceRechargeRequestsIdRoute =
  AuthenticatedFinanceRechargeRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFinanceRechargeRequestsRoute,
  } as any)
const AuthenticatedFinanceRechargeRefundsIdRoute =
  AuthenticatedFinanceRechargeRefundsIdRouteImport.update({
    id: '/recharge-refunds/$id',
    path: '/recharge-refunds/$id',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinancePackagesIdRoute =
  AuthenticatedFinancePackagesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFinancePackagesRoute,
  } as any)
const ApiPublicWebhooksPaymentsGatewayIdRefundsRoute =
  ApiPublicWebhooksPaymentsGatewayIdRefundsRouteImport.update({
    id: '/api/public/webhooks/payments/$gatewayId/refunds',
    path: '/api/public/webhooks/payments/$gatewayId/refunds',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account-deletions': typeof AuthenticatedAccountDeletionsRoute
  '/admins': typeof AuthenticatedAdminsRouteWithChildren
  '/agencies': typeof AuthenticatedAgenciesRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/app-releases': typeof AuthenticatedAppReleasesRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/bd': typeof AuthenticatedBdRouteWithChildren
  '/charging-agencies': typeof AuthenticatedChargingAgenciesRouteWithChildren
  '/charging-agents': typeof AuthenticatedChargingAgentsRouteWithChildren
  '/charging-coin-transfers': typeof AuthenticatedChargingCoinTransfersRoute
  '/charging-pearl-transfers': typeof AuthenticatedChargingPearlTransfersRoute
  '/charging-pricing': typeof AuthenticatedChargingPricingRoute
  '/daily-login': typeof AuthenticatedDailyLoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distinctive-ids': typeof AuthenticatedDistinctiveIdsRoute
  '/economy': typeof AuthenticatedEconomyRoute
  '/events': typeof AuthenticatedEventsRoute
  '/families': typeof AuthenticatedFamiliesRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/games': typeof AuthenticatedGamesRoute
  '/gifts': typeof AuthenticatedGiftsRoute
  '/host-transfer-requests': typeof AuthenticatedHostTransferRequestsRoute
  '/hosts': typeof AuthenticatedHostsRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/system-messages': typeof AuthenticatedSystemMessagesRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/pearl-coin-exchanges': typeof AuthenticatedPearlCoinExchangesRoute
  '/pearl-purchases': typeof AuthenticatedPearlPurchasesRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/relationships': typeof AuthenticatedRelationshipsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/security-check': typeof AuthenticatedSecurityCheckRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/support-tickets': typeof AuthenticatedSupportTicketsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/verifications': typeof AuthenticatedVerificationsRoute
  '/vip-levels': typeof AuthenticatedVipLevelsRoute
  '/wallet-adjustments': typeof AuthenticatedWalletAdjustmentsRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/admins/invites': typeof AuthenticatedAdminsInvitesRoute
  '/agencies/$id': typeof AuthenticatedAgenciesIdRoute
  '/bd/$id': typeof AuthenticatedBdIdRoute
  '/charging-agencies/$id': typeof AuthenticatedChargingAgenciesIdRoute
  '/charging-agents/$id': typeof AuthenticatedChargingAgentsIdRoute
  '/finance/coin-prices': typeof AuthenticatedFinanceCoinPricesRoute
  '/finance/gateways': typeof AuthenticatedFinanceGatewaysRoute
  '/finance/packages': typeof AuthenticatedFinancePackagesRouteWithChildren
  '/finance/payment-methods': typeof AuthenticatedFinancePaymentMethodsRoute
  '/finance/pearl-prices': typeof AuthenticatedFinancePearlPricesRoute
  '/finance/recharge-requests': typeof AuthenticatedFinanceRechargeRequestsRouteWithChildren
  '/finance/reports': typeof AuthenticatedFinanceReportsRoute
  '/finance/withdrawal-requests': typeof AuthenticatedFinanceWithdrawalRequestsRoute
  '/finance/withdrawal-settings': typeof AuthenticatedFinanceWithdrawalSettingsRoute
  '/hosts/$id': typeof AuthenticatedHostsIdRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/finance/packages/$id': typeof AuthenticatedFinancePackagesIdRoute
  '/finance/recharge-refunds/$id': typeof AuthenticatedFinanceRechargeRefundsIdRoute
  '/finance/recharge-requests/$id': typeof AuthenticatedFinanceRechargeRequestsIdRoute
  '/finance/recharge-refunds/': typeof AuthenticatedFinanceRechargeRefundsIndexRoute
  '/api/public/webhooks/payments/$gatewayId/refunds': typeof ApiPublicWebhooksPaymentsGatewayIdRefundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account-deletions': typeof AuthenticatedAccountDeletionsRoute
  '/admins': typeof AuthenticatedAdminsRouteWithChildren
  '/agencies': typeof AuthenticatedAgenciesRouteWithChildren
  '/ai': typeof AuthenticatedAiRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/app-releases': typeof AuthenticatedAppReleasesRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/bd': typeof AuthenticatedBdRouteWithChildren
  '/charging-agencies': typeof AuthenticatedChargingAgenciesRouteWithChildren
  '/charging-agents': typeof AuthenticatedChargingAgentsRouteWithChildren
  '/charging-coin-transfers': typeof AuthenticatedChargingCoinTransfersRoute
  '/charging-pearl-transfers': typeof AuthenticatedChargingPearlTransfersRoute
  '/charging-pricing': typeof AuthenticatedChargingPricingRoute
  '/daily-login': typeof AuthenticatedDailyLoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distinctive-ids': typeof AuthenticatedDistinctiveIdsRoute
  '/economy': typeof AuthenticatedEconomyRoute
  '/events': typeof AuthenticatedEventsRoute
  '/families': typeof AuthenticatedFamiliesRoute
  '/games': typeof AuthenticatedGamesRoute
  '/gifts': typeof AuthenticatedGiftsRoute
  '/host-transfer-requests': typeof AuthenticatedHostTransferRequestsRoute
  '/hosts': typeof AuthenticatedHostsRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/system-messages': typeof AuthenticatedSystemMessagesRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/pearl-coin-exchanges': typeof AuthenticatedPearlCoinExchangesRoute
  '/pearl-purchases': typeof AuthenticatedPearlPurchasesRoute
  '/posts': typeof AuthenticatedPostsRoute
  '/relationships': typeof AuthenticatedRelationshipsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/security-check': typeof AuthenticatedSecurityCheckRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/support-tickets': typeof AuthenticatedSupportTicketsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/verifications': typeof AuthenticatedVerificationsRoute
  '/vip-levels': typeof AuthenticatedVipLevelsRoute
  '/wallet-adjustments': typeof AuthenticatedWalletAdjustmentsRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/admins/invites': typeof AuthenticatedAdminsInvitesRoute
  '/agencies/$id': typeof AuthenticatedAgenciesIdRoute
  '/bd/$id': typeof AuthenticatedBdIdRoute
  '/charging-agencies/$id': typeof AuthenticatedChargingAgenciesIdRoute
  '/charging-agents/$id': typeof AuthenticatedChargingAgentsIdRoute
  '/finance/coin-prices': typeof AuthenticatedFinanceCoinPricesRoute
  '/finance/gateways': typeof AuthenticatedFinanceGatewaysRoute
  '/finance/packages': typeof AuthenticatedFinancePackagesRouteWithChildren
  '/finance/payment-methods': typeof AuthenticatedFinancePaymentMethodsRoute
  '/finance/pearl-prices': typeof AuthenticatedFinancePearlPricesRoute
  '/finance/recharge-requests': typeof AuthenticatedFinanceRechargeRequestsRouteWithChildren
  '/finance/reports': typeof AuthenticatedFinanceReportsRoute
  '/finance/withdrawal-requests': typeof AuthenticatedFinanceWithdrawalRequestsRoute
  '/finance/withdrawal-settings': typeof AuthenticatedFinanceWithdrawalSettingsRoute
  '/hosts/$id': typeof AuthenticatedHostsIdRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/finance/packages/$id': typeof AuthenticatedFinancePackagesIdRoute
  '/finance/recharge-refunds/$id': typeof AuthenticatedFinanceRechargeRefundsIdRoute
  '/finance/recharge-requests/$id': typeof AuthenticatedFinanceRechargeRequestsIdRoute
  '/finance/recharge-refunds': typeof AuthenticatedFinanceRechargeRefundsIndexRoute
  '/api/public/webhooks/payments/$gatewayId/refunds': typeof ApiPublicWebhooksPaymentsGatewayIdRefundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account-deletions': typeof AuthenticatedAccountDeletionsRoute
  '/_authenticated/admins': typeof AuthenticatedAdminsRouteWithChildren
  '/_authenticated/agencies': typeof AuthenticatedAgenciesRouteWithChildren
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/app-releases': typeof AuthenticatedAppReleasesRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/banners': typeof AuthenticatedBannersRoute
  '/_authenticated/bd': typeof AuthenticatedBdRouteWithChildren
  '/_authenticated/charging-agencies': typeof AuthenticatedChargingAgenciesRouteWithChildren
  '/_authenticated/charging-agents': typeof AuthenticatedChargingAgentsRouteWithChildren
  '/_authenticated/charging-coin-transfers': typeof AuthenticatedChargingCoinTransfersRoute
  '/_authenticated/charging-pearl-transfers': typeof AuthenticatedChargingPearlTransfersRoute
  '/_authenticated/charging-pricing': typeof AuthenticatedChargingPricingRoute
  '/_authenticated/daily-login': typeof AuthenticatedDailyLoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/distinctive-ids': typeof AuthenticatedDistinctiveIdsRoute
  '/_authenticated/economy': typeof AuthenticatedEconomyRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/families': typeof AuthenticatedFamiliesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/gifts': typeof AuthenticatedGiftsRoute
  '/_authenticated/host-transfer-requests': typeof AuthenticatedHostTransferRequestsRoute
  '/_authenticated/hosts': typeof AuthenticatedHostsRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/system-messages': typeof AuthenticatedSystemMessagesRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/pearl-coin-exchanges': typeof AuthenticatedPearlCoinExchangesRoute
  '/_authenticated/pearl-purchases': typeof AuthenticatedPearlPurchasesRoute
  '/_authenticated/posts': typeof AuthenticatedPostsRoute
  '/_authenticated/relationships': typeof AuthenticatedRelationshipsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/security-check': typeof AuthenticatedSecurityCheckRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/_authenticated/support-tickets': typeof AuthenticatedSupportTicketsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/verifications': typeof AuthenticatedVerificationsRoute
  '/_authenticated/vip-levels': typeof AuthenticatedVipLevelsRoute
  '/_authenticated/wallet-adjustments': typeof AuthenticatedWalletAdjustmentsRoute
  '/_authenticated/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/_authenticated/admins/invites': typeof AuthenticatedAdminsInvitesRoute
  '/_authenticated/agencies/$id': typeof AuthenticatedAgenciesIdRoute
  '/_authenticated/bd/$id': typeof AuthenticatedBdIdRoute
  '/_authenticated/charging-agencies/$id': typeof AuthenticatedChargingAgenciesIdRoute
  '/_authenticated/charging-agents/$id': typeof AuthenticatedChargingAgentsIdRoute
  '/_authenticated/finance/coin-prices': typeof AuthenticatedFinanceCoinPricesRoute
  '/_authenticated/finance/gateways': typeof AuthenticatedFinanceGatewaysRoute
  '/_authenticated/finance/packages': typeof AuthenticatedFinancePackagesRouteWithChildren
  '/_authenticated/finance/payment-methods': typeof AuthenticatedFinancePaymentMethodsRoute
  '/_authenticated/finance/pearl-prices': typeof AuthenticatedFinancePearlPricesRoute
  '/_authenticated/finance/recharge-requests': typeof AuthenticatedFinanceRechargeRequestsRouteWithChildren
  '/_authenticated/finance/reports': typeof AuthenticatedFinanceReportsRoute
  '/_authenticated/finance/withdrawal-requests': typeof AuthenticatedFinanceWithdrawalRequestsRoute
  '/_authenticated/finance/withdrawal-settings': typeof AuthenticatedFinanceWithdrawalSettingsRoute
  '/_authenticated/hosts/$id': typeof AuthenticatedHostsIdRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/finance/packages/$id': typeof AuthenticatedFinancePackagesIdRoute
  '/_authenticated/finance/recharge-refunds/$id': typeof AuthenticatedFinanceRechargeRefundsIdRoute
  '/_authenticated/finance/recharge-requests/$id': typeof AuthenticatedFinanceRechargeRequestsIdRoute
  '/_authenticated/finance/recharge-refunds/': typeof AuthenticatedFinanceRechargeRefundsIndexRoute
  '/api/public/webhooks/payments/$gatewayId/refunds': typeof ApiPublicWebhooksPaymentsGatewayIdRefundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account-deletions'
    | '/admins'
    | '/agencies'
    | '/ai'
    | '/analytics'
    | '/app-releases'
    | '/audit'
    | '/banners'
    | '/bd'
    | '/charging-agencies'
    | '/charging-agents'
    | '/charging-coin-transfers'
    | '/charging-pearl-transfers'
    | '/charging-pricing'
    | '/daily-login'
    | '/dashboard'
    | '/distinctive-ids'
    | '/economy'
    | '/events'
    | '/families'
    | '/finance'
    | '/games'
    | '/gifts'
    | '/host-transfer-requests'
    | '/hosts'
    | '/inventory'
    | '/messages'
    | '/moderation'
    | '/notifications'
    | '/system-messages'
    | '/operations'
    | '/pearl-coin-exchanges'
    | '/pearl-purchases'
    | '/posts'
    | '/relationships'
    | '/reports'
    | '/rooms'
    | '/security-check'
    | '/settings'
    | '/store'
    | '/support-tickets'
    | '/users'
    | '/verifications'
    | '/vip-levels'
    | '/wallet-adjustments'
    | '/withdrawals'
    | '/admins/invites'
    | '/agencies/$id'
    | '/bd/$id'
    | '/charging-agencies/$id'
    | '/charging-agents/$id'
    | '/finance/coin-prices'
    | '/finance/gateways'
    | '/finance/packages'
    | '/finance/payment-methods'
    | '/finance/pearl-prices'
    | '/finance/recharge-requests'
    | '/finance/reports'
    | '/finance/withdrawal-requests'
    | '/finance/withdrawal-settings'
    | '/hosts/$id'
    | '/users/$id'
    | '/finance/'
    | '/finance/packages/$id'
    | '/finance/recharge-refunds/$id'
    | '/finance/recharge-requests/$id'
    | '/finance/recharge-refunds/'
    | '/api/public/webhooks/payments/$gatewayId/refunds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account-deletions'
    | '/admins'
    | '/agencies'
    | '/ai'
    | '/analytics'
    | '/app-releases'
    | '/audit'
    | '/banners'
    | '/bd'
    | '/charging-agencies'
    | '/charging-agents'
    | '/charging-coin-transfers'
    | '/charging-pearl-transfers'
    | '/charging-pricing'
    | '/daily-login'
    | '/dashboard'
    | '/distinctive-ids'
    | '/economy'
    | '/events'
    | '/families'
    | '/games'
    | '/gifts'
    | '/host-transfer-requests'
    | '/hosts'
    | '/inventory'
    | '/messages'
    | '/moderation'
    | '/notifications'
    | '/system-messages'
    | '/operations'
    | '/pearl-coin-exchanges'
    | '/pearl-purchases'
    | '/posts'
    | '/relationships'
    | '/reports'
    | '/rooms'
    | '/security-check'
    | '/settings'
    | '/store'
    | '/support-tickets'
    | '/users'
    | '/verifications'
    | '/vip-levels'
    | '/wallet-adjustments'
    | '/withdrawals'
    | '/admins/invites'
    | '/agencies/$id'
    | '/bd/$id'
    | '/charging-agencies/$id'
    | '/charging-agents/$id'
    | '/finance/coin-prices'
    | '/finance/gateways'
    | '/finance/packages'
    | '/finance/payment-methods'
    | '/finance/pearl-prices'
    | '/finance/recharge-requests'
    | '/finance/reports'
    | '/finance/withdrawal-requests'
    | '/finance/withdrawal-settings'
    | '/hosts/$id'
    | '/users/$id'
    | '/finance'
    | '/finance/packages/$id'
    | '/finance/recharge-refunds/$id'
    | '/finance/recharge-requests/$id'
    | '/finance/recharge-refunds'
    | '/api/public/webhooks/payments/$gatewayId/refunds'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account-deletions'
    | '/_authenticated/admins'
    | '/_authenticated/agencies'
    | '/_authenticated/ai'
    | '/_authenticated/analytics'
    | '/_authenticated/app-releases'
    | '/_authenticated/audit'
    | '/_authenticated/banners'
    | '/_authenticated/bd'
    | '/_authenticated/charging-agencies'
    | '/_authenticated/charging-agents'
    | '/_authenticated/charging-coin-transfers'
    | '/_authenticated/charging-pearl-transfers'
    | '/_authenticated/charging-pricing'
    | '/_authenticated/daily-login'
    | '/_authenticated/dashboard'
    | '/_authenticated/distinctive-ids'
    | '/_authenticated/economy'
    | '/_authenticated/events'
    | '/_authenticated/families'
    | '/_authenticated/finance'
    | '/_authenticated/games'
    | '/_authenticated/gifts'
    | '/_authenticated/host-transfer-requests'
    | '/_authenticated/hosts'
    | '/_authenticated/inventory'
    | '/_authenticated/messages'
    | '/_authenticated/moderation'
    | '/_authenticated/notifications'
    | '/_authenticated/system-messages'
    | '/_authenticated/operations'
    | '/_authenticated/pearl-coin-exchanges'
    | '/_authenticated/pearl-purchases'
    | '/_authenticated/posts'
    | '/_authenticated/relationships'
    | '/_authenticated/reports'
    | '/_authenticated/rooms'
    | '/_authenticated/security-check'
    | '/_authenticated/settings'
    | '/_authenticated/store'
    | '/_authenticated/support-tickets'
    | '/_authenticated/users'
    | '/_authenticated/verifications'
    | '/_authenticated/vip-levels'
    | '/_authenticated/wallet-adjustments'
    | '/_authenticated/withdrawals'
    | '/_authenticated/admins/invites'
    | '/_authenticated/agencies/$id'
    | '/_authenticated/bd/$id'
    | '/_authenticated/charging-agencies/$id'
    | '/_authenticated/charging-agents/$id'
    | '/_authenticated/finance/coin-prices'
    | '/_authenticated/finance/gateways'
    | '/_authenticated/finance/packages'
    | '/_authenticated/finance/payment-methods'
    | '/_authenticated/finance/pearl-prices'
    | '/_authenticated/finance/recharge-requests'
    | '/_authenticated/finance/reports'
    | '/_authenticated/finance/withdrawal-requests'
    | '/_authenticated/finance/withdrawal-settings'
    | '/_authenticated/hosts/$id'
    | '/_authenticated/users/$id'
    | '/_authenticated/finance/'
    | '/_authenticated/finance/packages/$id'
    | '/_authenticated/finance/recharge-refunds/$id'
    | '/_authenticated/finance/recharge-requests/$id'
    | '/_authenticated/finance/recharge-refunds/'
    | '/api/public/webhooks/payments/$gatewayId/refunds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWebhooksPaymentsGatewayIdRefundsRoute: typeof ApiPublicWebhooksPaymentsGatewayIdRefundsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdrawals': {
      id: '/_authenticated/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof AuthenticatedWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet-adjustments': {
      id: '/_authenticated/wallet-adjustments'
      path: '/wallet-adjustments'
      fullPath: '/wallet-adjustments'
      preLoaderRoute: typeof AuthenticatedWalletAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip-levels': {
      id: '/_authenticated/vip-levels'
      path: '/vip-levels'
      fullPath: '/vip-levels'
      preLoaderRoute: typeof AuthenticatedVipLevelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verifications': {
      id: '/_authenticated/verifications'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof AuthenticatedVerificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support-tickets': {
      id: '/_authenticated/support-tickets'
      path: '/support-tickets'
      fullPath: '/support-tickets'
      preLoaderRoute: typeof AuthenticatedSupportTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security-check': {
      id: '/_authenticated/security-check'
      path: '/security-check'
      fullPath: '/security-check'
      preLoaderRoute: typeof AuthenticatedSecurityCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relationships': {
      id: '/_authenticated/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof AuthenticatedRelationshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts': {
      id: '/_authenticated/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthenticatedPostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pearl-purchases': {
      id: '/_authenticated/pearl-purchases'
      path: '/pearl-purchases'
      fullPath: '/pearl-purchases'
      preLoaderRoute: typeof AuthenticatedPearlPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pearl-coin-exchanges': {
      id: '/_authenticated/pearl-coin-exchanges'
      path: '/pearl-coin-exchanges'
      fullPath: '/pearl-coin-exchanges'
      preLoaderRoute: typeof AuthenticatedPearlCoinExchangesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-messages': {
      id: '/_authenticated/system-messages'
      path: '/system-messages'
      fullPath: '/system-messages'
      preLoaderRoute: typeof AuthenticatedSystemMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hosts': {
      id: '/_authenticated/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof AuthenticatedHostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host-transfer-requests': {
      id: '/_authenticated/host-transfer-requests'
      path: '/host-transfer-requests'
      fullPath: '/host-transfer-requests'
      preLoaderRoute: typeof AuthenticatedHostTransferRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gifts': {
      id: '/_authenticated/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof AuthenticatedGiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/families': {
      id: '/_authenticated/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof AuthenticatedFamiliesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/economy': {
      id: '/_authenticated/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof AuthenticatedEconomyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distinctive-ids': {
      id: '/_authenticated/distinctive-ids'
      path: '/distinctive-ids'
      fullPath: '/distinctive-ids'
      preLoaderRoute: typeof AuthenticatedDistinctiveIdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-login': {
      id: '/_authenticated/daily-login'
      path: '/daily-login'
      fullPath: '/daily-login'
      preLoaderRoute: typeof AuthenticatedDailyLoginRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charging-pricing': {
      id: '/_authenticated/charging-pricing'
      path: '/charging-pricing'
      fullPath: '/charging-pricing'
      preLoaderRoute: typeof AuthenticatedChargingPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charging-pearl-transfers': {
      id: '/_authenticated/charging-pearl-transfers'
      path: '/charging-pearl-transfers'
      fullPath: '/charging-pearl-transfers'
      preLoaderRoute: typeof AuthenticatedChargingPearlTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charging-coin-transfers': {
      id: '/_authenticated/charging-coin-transfers'
      path: '/charging-coin-transfers'
      fullPath: '/charging-coin-transfers'
      preLoaderRoute: typeof AuthenticatedChargingCoinTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charging-agents': {
      id: '/_authenticated/charging-agents'
      path: '/charging-agents'
      fullPath: '/charging-agents'
      preLoaderRoute: typeof AuthenticatedChargingAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charging-agencies': {
      id: '/_authenticated/charging-agencies'
      path: '/charging-agencies'
      fullPath: '/charging-agencies'
      preLoaderRoute: typeof AuthenticatedChargingAgenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bd': {
      id: '/_authenticated/bd'
      path: '/bd'
      fullPath: '/bd'
      preLoaderRoute: typeof AuthenticatedBdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banners': {
      id: '/_authenticated/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AuthenticatedBannersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app-releases': {
      id: '/_authenticated/app-releases'
      path: '/app-releases'
      fullPath: '/app-releases'
      preLoaderRoute: typeof AuthenticatedAppReleasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencies': {
      id: '/_authenticated/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AuthenticatedAgenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admins': {
      id: '/_authenticated/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthenticatedAdminsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-deletions': {
      id: '/_authenticated/account-deletions'
      path: '/account-deletions'
      fullPath: '/account-deletions'
      preLoaderRoute: typeof AuthenticatedAccountDeletionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/hosts/$id': {
      id: '/_authenticated/hosts/$id'
      path: '/$id'
      fullPath: '/hosts/$id'
      preLoaderRoute: typeof AuthenticatedHostsIdRouteImport
      parentRoute: typeof AuthenticatedHostsRoute
    }
    '/_authenticated/finance/withdrawal-settings': {
      id: '/_authenticated/finance/withdrawal-settings'
      path: '/withdrawal-settings'
      fullPath: '/finance/withdrawal-settings'
      preLoaderRoute: typeof AuthenticatedFinanceWithdrawalSettingsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/withdrawal-requests': {
      id: '/_authenticated/finance/withdrawal-requests'
      path: '/withdrawal-requests'
      fullPath: '/finance/withdrawal-requests'
      preLoaderRoute: typeof AuthenticatedFinanceWithdrawalRequestsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/reports': {
      id: '/_authenticated/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof AuthenticatedFinanceReportsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/recharge-requests': {
      id: '/_authenticated/finance/recharge-requests'
      path: '/recharge-requests'
      fullPath: '/finance/recharge-requests'
      preLoaderRoute: typeof AuthenticatedFinanceRechargeRequestsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/pearl-prices': {
      id: '/_authenticated/finance/pearl-prices'
      path: '/pearl-prices'
      fullPath: '/finance/pearl-prices'
      preLoaderRoute: typeof AuthenticatedFinancePearlPricesRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/payment-methods': {
      id: '/_authenticated/finance/payment-methods'
      path: '/payment-methods'
      fullPath: '/finance/payment-methods'
      preLoaderRoute: typeof AuthenticatedFinancePaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/packages': {
      id: '/_authenticated/finance/packages'
      path: '/packages'
      fullPath: '/finance/packages'
      preLoaderRoute: typeof AuthenticatedFinancePackagesRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/gateways': {
      id: '/_authenticated/finance/gateways'
      path: '/gateways'
      fullPath: '/finance/gateways'
      preLoaderRoute: typeof AuthenticatedFinanceGatewaysRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/coin-prices': {
      id: '/_authenticated/finance/coin-prices'
      path: '/coin-prices'
      fullPath: '/finance/coin-prices'
      preLoaderRoute: typeof AuthenticatedFinanceCoinPricesRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/charging-agents/$id': {
      id: '/_authenticated/charging-agents/$id'
      path: '/$id'
      fullPath: '/charging-agents/$id'
      preLoaderRoute: typeof AuthenticatedChargingAgentsIdRouteImport
      parentRoute: typeof AuthenticatedChargingAgentsRoute
    }
    '/_authenticated/charging-agencies/$id': {
      id: '/_authenticated/charging-agencies/$id'
      path: '/$id'
      fullPath: '/charging-agencies/$id'
      preLoaderRoute: typeof AuthenticatedChargingAgenciesIdRouteImport
      parentRoute: typeof AuthenticatedChargingAgenciesRoute
    }
    '/_authenticated/bd/$id': {
      id: '/_authenticated/bd/$id'
      path: '/$id'
      fullPath: '/bd/$id'
      preLoaderRoute: typeof AuthenticatedBdIdRouteImport
      parentRoute: typeof AuthenticatedBdRoute
    }
    '/_authenticated/agencies/$id': {
      id: '/_authenticated/agencies/$id'
      path: '/$id'
      fullPath: '/agencies/$id'
      preLoaderRoute: typeof AuthenticatedAgenciesIdRouteImport
      parentRoute: typeof AuthenticatedAgenciesRoute
    }
    '/_authenticated/admins/invites': {
      id: '/_authenticated/admins/invites'
      path: '/invites'
      fullPath: '/admins/invites'
      preLoaderRoute: typeof AuthenticatedAdminsInvitesRouteImport
      parentRoute: typeof AuthenticatedAdminsRoute
    }
    '/_authenticated/finance/recharge-refunds/': {
      id: '/_authenticated/finance/recharge-refunds/'
      path: '/recharge-refunds'
      fullPath: '/finance/recharge-refunds/'
      preLoaderRoute: typeof AuthenticatedFinanceRechargeRefundsIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/recharge-requests/$id': {
      id: '/_authenticated/finance/recharge-requests/$id'
      path: '/$id'
      fullPath: '/finance/recharge-requests/$id'
      preLoaderRoute: typeof AuthenticatedFinanceRechargeRequestsIdRouteImport
      parentRoute: typeof AuthenticatedFinanceRechargeRequestsRoute
    }
    '/_authenticated/finance/recharge-refunds/$id': {
      id: '/_authenticated/finance/recharge-refunds/$id'
      path: '/recharge-refunds/$id'
      fullPath: '/finance/recharge-refunds/$id'
      preLoaderRoute: typeof AuthenticatedFinanceRechargeRefundsIdRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/packages/$id': {
      id: '/_authenticated/finance/packages/$id'
      path: '/$id'
      fullPath: '/finance/packages/$id'
      preLoaderRoute: typeof AuthenticatedFinancePackagesIdRouteImport
      parentRoute: typeof AuthenticatedFinancePackagesRoute
    }
    '/api/public/webhooks/payments/$gatewayId/refunds': {
      id: '/api/public/webhooks/payments/$gatewayId/refunds'
      path: '/api/public/webhooks/payments/$gatewayId/refunds'
      fullPath: '/api/public/webhooks/payments/$gatewayId/refunds'
      preLoaderRoute: typeof ApiPublicWebhooksPaymentsGatewayIdRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminsRouteChildren {
  AuthenticatedAdminsInvitesRoute: typeof AuthenticatedAdminsInvitesRoute
}

const AuthenticatedAdminsRouteChildren: AuthenticatedAdminsRouteChildren = {
  AuthenticatedAdminsInvitesRoute: AuthenticatedAdminsInvitesRoute,
}

const AuthenticatedAdminsRouteWithChildren =
  AuthenticatedAdminsRoute._addFileChildren(AuthenticatedAdminsRouteChildren)

interface AuthenticatedAgenciesRouteChildren {
  AuthenticatedAgenciesIdRoute: typeof AuthenticatedAgenciesIdRoute
}

const AuthenticatedAgenciesRouteChildren: AuthenticatedAgenciesRouteChildren = {
  AuthenticatedAgenciesIdRoute: AuthenticatedAgenciesIdRoute,
}

const AuthenticatedAgenciesRouteWithChildren =
  AuthenticatedAgenciesRoute._addFileChildren(
    AuthenticatedAgenciesRouteChildren,
  )

interface AuthenticatedBdRouteChildren {
  AuthenticatedBdIdRoute: typeof AuthenticatedBdIdRoute
}

const AuthenticatedBdRouteChildren: AuthenticatedBdRouteChildren = {
  AuthenticatedBdIdRoute: AuthenticatedBdIdRoute,
}

const AuthenticatedBdRouteWithChildren = AuthenticatedBdRoute._addFileChildren(
  AuthenticatedBdRouteChildren,
)

interface AuthenticatedChargingAgenciesRouteChildren {
  AuthenticatedChargingAgenciesIdRoute: typeof AuthenticatedChargingAgenciesIdRoute
}

const AuthenticatedChargingAgenciesRouteChildren: AuthenticatedChargingAgenciesRouteChildren =
  {
    AuthenticatedChargingAgenciesIdRoute: AuthenticatedChargingAgenciesIdRoute,
  }

const AuthenticatedChargingAgenciesRouteWithChildren =
  AuthenticatedChargingAgenciesRoute._addFileChildren(
    AuthenticatedChargingAgenciesRouteChildren,
  )

interface AuthenticatedChargingAgentsRouteChildren {
  AuthenticatedChargingAgentsIdRoute: typeof AuthenticatedChargingAgentsIdRoute
}

const AuthenticatedChargingAgentsRouteChildren: AuthenticatedChargingAgentsRouteChildren =
  {
    AuthenticatedChargingAgentsIdRoute: AuthenticatedChargingAgentsIdRoute,
  }

const AuthenticatedChargingAgentsRouteWithChildren =
  AuthenticatedChargingAgentsRoute._addFileChildren(
    AuthenticatedChargingAgentsRouteChildren,
  )

interface AuthenticatedFinancePackagesRouteChildren {
  AuthenticatedFinancePackagesIdRoute: typeof AuthenticatedFinancePackagesIdRoute
}

const AuthenticatedFinancePackagesRouteChildren: AuthenticatedFinancePackagesRouteChildren =
  {
    AuthenticatedFinancePackagesIdRoute: AuthenticatedFinancePackagesIdRoute,
  }

const AuthenticatedFinancePackagesRouteWithChildren =
  AuthenticatedFinancePackagesRoute._addFileChildren(
    AuthenticatedFinancePackagesRouteChildren,
  )

interface AuthenticatedFinanceRechargeRequestsRouteChildren {
  AuthenticatedFinanceRechargeRequestsIdRoute: typeof AuthenticatedFinanceRechargeRequestsIdRoute
}

const AuthenticatedFinanceRechargeRequestsRouteChildren: AuthenticatedFinanceRechargeRequestsRouteChildren =
  {
    AuthenticatedFinanceRechargeRequestsIdRoute:
      AuthenticatedFinanceRechargeRequestsIdRoute,
  }

const AuthenticatedFinanceRechargeRequestsRouteWithChildren =
  AuthenticatedFinanceRechargeRequestsRoute._addFileChildren(
    AuthenticatedFinanceRechargeRequestsRouteChildren,
  )

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceCoinPricesRoute: typeof AuthenticatedFinanceCoinPricesRoute
  AuthenticatedFinanceGatewaysRoute: typeof AuthenticatedFinanceGatewaysRoute
  AuthenticatedFinancePackagesRoute: typeof AuthenticatedFinancePackagesRouteWithChildren
  AuthenticatedFinancePaymentMethodsRoute: typeof AuthenticatedFinancePaymentMethodsRoute
  AuthenticatedFinancePearlPricesRoute: typeof AuthenticatedFinancePearlPricesRoute
  AuthenticatedFinanceRechargeRequestsRoute: typeof AuthenticatedFinanceRechargeRequestsRouteWithChildren
  AuthenticatedFinanceReportsRoute: typeof AuthenticatedFinanceReportsRoute
  AuthenticatedFinanceWithdrawalRequestsRoute: typeof AuthenticatedFinanceWithdrawalRequestsRoute
  AuthenticatedFinanceWithdrawalSettingsRoute: typeof AuthenticatedFinanceWithdrawalSettingsRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
  AuthenticatedFinanceRechargeRefundsIdRoute: typeof AuthenticatedFinanceRechargeRefundsIdRoute
  AuthenticatedFinanceRechargeRefundsIndexRoute: typeof AuthenticatedFinanceRechargeRefundsIndexRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceCoinPricesRoute: AuthenticatedFinanceCoinPricesRoute,
  AuthenticatedFinanceGatewaysRoute: AuthenticatedFinanceGatewaysRoute,
  AuthenticatedFinancePackagesRoute:
    AuthenticatedFinancePackagesRouteWithChildren,
  AuthenticatedFinancePaymentMethodsRoute:
    AuthenticatedFinancePaymentMethodsRoute,
  AuthenticatedFinancePearlPricesRoute: AuthenticatedFinancePearlPricesRoute,
  AuthenticatedFinanceRechargeRequestsRoute:
    AuthenticatedFinanceRechargeRequestsRouteWithChildren,
  AuthenticatedFinanceReportsRoute: AuthenticatedFinanceReportsRoute,
  AuthenticatedFinanceWithdrawalRequestsRoute:
    AuthenticatedFinanceWithdrawalRequestsRoute,
  AuthenticatedFinanceWithdrawalSettingsRoute:
    AuthenticatedFinanceWithdrawalSettingsRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
  AuthenticatedFinanceRechargeRefundsIdRoute:
    AuthenticatedFinanceRechargeRefundsIdRoute,
  AuthenticatedFinanceRechargeRefundsIndexRoute:
    AuthenticatedFinanceRechargeRefundsIndexRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedHostsRouteChildren {
  AuthenticatedHostsIdRoute: typeof AuthenticatedHostsIdRoute
}

const AuthenticatedHostsRouteChildren: AuthenticatedHostsRouteChildren = {
  AuthenticatedHostsIdRoute: AuthenticatedHostsIdRoute,
}

const AuthenticatedHostsRouteWithChildren =
  AuthenticatedHostsRoute._addFileChildren(AuthenticatedHostsRouteChildren)

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountDeletionsRoute: typeof AuthenticatedAccountDeletionsRoute
  AuthenticatedAdminsRoute: typeof AuthenticatedAdminsRouteWithChildren
  AuthenticatedAgenciesRoute: typeof AuthenticatedAgenciesRouteWithChildren
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAppReleasesRoute: typeof AuthenticatedAppReleasesRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBannersRoute: typeof AuthenticatedBannersRoute
  AuthenticatedBdRoute: typeof AuthenticatedBdRouteWithChildren
  AuthenticatedChargingAgenciesRoute: typeof AuthenticatedChargingAgenciesRouteWithChildren
  AuthenticatedChargingAgentsRoute: typeof AuthenticatedChargingAgentsRouteWithChildren
  AuthenticatedChargingCoinTransfersRoute: typeof AuthenticatedChargingCoinTransfersRoute
  AuthenticatedChargingPearlTransfersRoute: typeof AuthenticatedChargingPearlTransfersRoute
  AuthenticatedChargingPricingRoute: typeof AuthenticatedChargingPricingRoute
  AuthenticatedDailyLoginRoute: typeof AuthenticatedDailyLoginRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistinctiveIdsRoute: typeof AuthenticatedDistinctiveIdsRoute
  AuthenticatedEconomyRoute: typeof AuthenticatedEconomyRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedFamiliesRoute: typeof AuthenticatedFamiliesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedGiftsRoute: typeof AuthenticatedGiftsRoute
  AuthenticatedHostTransferRequestsRoute: typeof AuthenticatedHostTransferRequestsRoute
  AuthenticatedHostsRoute: typeof AuthenticatedHostsRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSystemMessagesRoute: typeof AuthenticatedSystemMessagesRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedPearlCoinExchangesRoute: typeof AuthenticatedPearlCoinExchangesRoute
  AuthenticatedPearlPurchasesRoute: typeof AuthenticatedPearlPurchasesRoute
  AuthenticatedPostsRoute: typeof AuthenticatedPostsRoute
  AuthenticatedRelationshipsRoute: typeof AuthenticatedRelationshipsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedSecurityCheckRoute: typeof AuthenticatedSecurityCheckRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedSupportTicketsRoute: typeof AuthenticatedSupportTicketsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedVerificationsRoute: typeof AuthenticatedVerificationsRoute
  AuthenticatedVipLevelsRoute: typeof AuthenticatedVipLevelsRoute
  AuthenticatedWalletAdjustmentsRoute: typeof AuthenticatedWalletAdjustmentsRoute
  AuthenticatedWithdrawalsRoute: typeof AuthenticatedWithdrawalsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountDeletionsRoute: AuthenticatedAccountDeletionsRoute,
  AuthenticatedAdminsRoute: AuthenticatedAdminsRouteWithChildren,
  AuthenticatedAgenciesRoute: AuthenticatedAgenciesRouteWithChildren,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAppReleasesRoute: AuthenticatedAppReleasesRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBannersRoute: AuthenticatedBannersRoute,
  AuthenticatedBdRoute: AuthenticatedBdRouteWithChildren,
  AuthenticatedChargingAgenciesRoute:
    AuthenticatedChargingAgenciesRouteWithChildren,
  AuthenticatedChargingAgentsRoute:
    AuthenticatedChargingAgentsRouteWithChildren,
  AuthenticatedChargingCoinTransfersRoute:
    AuthenticatedChargingCoinTransfersRoute,
  AuthenticatedChargingPearlTransfersRoute:
    AuthenticatedChargingPearlTransfersRoute,
  AuthenticatedChargingPricingRoute: AuthenticatedChargingPricingRoute,
  AuthenticatedDailyLoginRoute: AuthenticatedDailyLoginRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistinctiveIdsRoute: AuthenticatedDistinctiveIdsRoute,
  AuthenticatedEconomyRoute: AuthenticatedEconomyRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedFamiliesRoute: AuthenticatedFamiliesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedGiftsRoute: AuthenticatedGiftsRoute,
  AuthenticatedHostTransferRequestsRoute:
    AuthenticatedHostTransferRequestsRoute,
  AuthenticatedHostsRoute: AuthenticatedHostsRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSystemMessagesRoute: AuthenticatedSystemMessagesRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedPearlCoinExchangesRoute: AuthenticatedPearlCoinExchangesRoute,
  AuthenticatedPearlPurchasesRoute: AuthenticatedPearlPurchasesRoute,
  AuthenticatedPostsRoute: AuthenticatedPostsRoute,
  AuthenticatedRelationshipsRoute: AuthenticatedRelationshipsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedSecurityCheckRoute: AuthenticatedSecurityCheckRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedSupportTicketsRoute: AuthenticatedSupportTicketsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedVerificationsRoute: AuthenticatedVerificationsRoute,
  AuthenticatedVipLevelsRoute: AuthenticatedVipLevelsRoute,
  AuthenticatedWalletAdjustmentsRoute: AuthenticatedWalletAdjustmentsRoute,
  AuthenticatedWithdrawalsRoute: AuthenticatedWithdrawalsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWebhooksPaymentsGatewayIdRefundsRoute:
    ApiPublicWebhooksPaymentsGatewayIdRefundsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
